data_volumes:
  build: ./volumes
  volumes:
    - ./volumes:/docker_volumes
nginx:
  build: ./nginx
  links:
    - node_server:node_server
  volumes:
    - ./volumes:/docker_volumes
  ports:
    - "5000:80"
mongodb:
  build: ./mongodb
  volumes_from:
    - data_volumes
  ports:
    - "27017:27017"   
node_server:
  build: ./node_app
  links:
    - mongodb:mongodb
  volumes_from:
    - data_volumes
  environment:
    - PORT=3002
  ports:
    - "3002:3002"